/**
 * SFL 敵人資料庫
 * 根據 data/e1~e10.txt 敵人資料建立
 */
const ENEMY_DATABASE = [
    {
        id: 'e1',
        name: '白金使者',
        description: '鋼鐵都市深處，機構異常震動。伴隨著雷光閃現，一名白金色身影自空間裂隙中現形。「雷擊啟動——戰鬥模組上線。」白金使者低聲宣告，雙眼閃爍冷冽青光，雷鳴刀應聲出鞘，劍尖激盪電弧。',
        level: 30,
        attribute: '雷',
        hp: 15000,
        attack: 230,
        shield: 150,
        hit_rate: 90,
        evasion: 8,
        atk_speed: 150,
        shield_pen: 30
    },
    {
        id: 'e2',
        name: '幻境巨獸',
        description: '裂口撕開空間，巨爪橫掃而出。幻境巨獸咆哮著降臨，帶來扭曲現實的恐懼波動。牠是夢魘的源頭，能吞噬魔力與理智。這不是單純的戰鬥，而是生存考驗。準備迎戰潘朵拉的惡夢吧。',
        level: 50,
        attribute: '暗',
        hp: 31000,
        attack: 590,
        shield: 250,
        hit_rate: 100,
        evasion: 40,
        atk_speed: 200,
        shield_pen: 90
    },
    {
        id: 'e3',
        name: '神化信使',
        description: '它靜靜降臨，並未先攻擊，而是掃描全場。這不是尋常械具，而是代表「王命」的意志延伸。若你選擇對抗，便等同於向天啟王本人宣戰。神化信使，即將執行毀滅命令。',
        level: 70,
        attribute: '雷',
        hp: 80000,
        attack: 1200,
        shield: 400,
        hit_rate: 100,
        evasion: 20,
        atk_speed: 250,
        shield_pen: 100
    },
    {
        id: 'e4',
        name: '亞斯塔路',
        description: '「龍王教」五賢者之一，忠實踐行著阿瓦隆的命令。被指派在雲空大陸行動，隨著世間的紛爭與混亂而現身。手持蘊含混沌魔劍碎片之力的「混沌魔弓」，同時掌控火與冰兩種元素，因此亦有「冰與火的魔術師」之稱。',
        level: 90,
        attribute: '火、水',
        hp: 301000,
        attack: 4000,
        shield: 350,
        hit_rate: 120,
        evasion: 40,
        atk_speed: 300,
        shield_pen: 200
    },
    {
        id: 'e5',
        name: '主教墨洛伊克',
        description: '赤血教堂的樞機主教。在波羅斯賦予絕滅項鍊的焰火後，大火吞噬了他，卻未焚盡信仰。如今的他，只剩燃燒的骷髏與永不止息的獻祭之火。「信仰即焰，靈魂即薪。成為灰燼吧。」',
        level: 110,
        attribute: '火',
        hp: 400000,
        attack: 10000,
        shield: 400,
        hit_rate: 150,
        evasion: 50,
        atk_speed: 350,
        shield_pen: 300
    },
    {
        id: 'e6',
        name: '完全之龍．伊格斯邦',
        description: '吞噬希露薇亞後逃離並長大成為巨龍的伊格斯邦。仍然在追尋著自己存在的意義。「母親...，我將找到您...」',
        level: 130,
        attribute: '水',
        hp: 500000,
        attack: 22000,
        shield: 450,
        hit_rate: 200,
        evasion: 50,
        atk_speed: 350,
        shield_pen: 400
    },
    {
        id: 'e7',
        name: '卡姆蘭',
        description: '「我不是祂，我也不是祂的影子。」他凝視眾生，聲音飄渺。「造物主也是有想要看看世界的時候」有時候，那一位存在會捏出一個身體在伊甸徘徊，看看三界的現況。「但願阿瓦隆不會發現我。」',
        level: 150,
        attribute: '光',
        hp: 600000,
        attack: 30000,
        shield: 450,
        hit_rate: 200,
        evasion: 60,
        atk_speed: 400,
        shield_pen: 500
    },
    {
        id: 'e8',
        name: '菲妮克絲．尼克羅諾',
        description: '「請把尼克羅諾米肯的下落告訴我，好嗎？」她微笑著。尼克羅諾家族的大小姊，對家族失望至極，拋下中立的立場，選擇投向七罪帝國。「那本書原本就會是屬於我的。知道它在哪裡，是我的權利。」她的眼神仍舊溫柔，只是那份溫柔裡藏著令人發寒的空洞。「如果你們不願意說……那就讓靈魂代替你回答吧。」',
        level: 200,
        attribute: '暗',
        hp: 1000000,
        attack: 40000,
        shield: 650,
        hit_rate: 300,
        evasion: 60,
        atk_speed: 400,
        shield_pen: 500
    },
    {
        id: 'e9',
        name: '紗布．妮古拉斯',
        description: '「為何至今仍無人信奉阿撒托斯？」紗布．妮古拉斯低聲疑惑。它盤踞在卡達斯聖山上空已久，自認絕對的恐懼早已瀰漫整個舊日領域，卻始終未曾誕生能夠對抗「神秘」的人才。人們只是不斷被舊日魔物追殺、凌虐，毫無止境。「阿撒托斯，這真的是你所希望的嗎？」',
        level: 300,
        attribute: '無',
        hp: 2000000,
        attack: 40000,
        shield: 1000,
        hit_rate: 450,
        evasion: 60,
        atk_speed: 500,
        shield_pen: 700
    },
    {
        id: 'e10',
        name: '「櫻庭組老大」櫻代 久遠',
        description: '久遠先生看起來像個十三、四歲的少年。但要說他在櫻代家裡的位階肯定高過當代家主。他和櫻代屋敷地下的神祕的關係十分密切，地下鐵門上的封印只有當代家主和他能解除。',
        level: 400,
        attribute: '無',
        hp: 7000000,
        attack: 200000,
        shield: 1200,
        hit_rate: 300,
        evasion: 50,
        atk_speed: 500,
        shield_pen: 2500
    }
];
